89 frontend logic for deleting reviews
mGarbowski/pap-projekt pull request #123
Opened 2023-12-25 09:43 UTC by mbienkowsk

works fine except when backend doesn't let it delete (if a review has comments), not sure if it should be merged before that issue is fixed

2023-12-27 16:22 UTC, mGarbowski requested changes
wygląda ok, ale nie mergujemy tego dopóki nie będzie działać też przy istniejących komentarzach i pare innych rzeczy jest do poprawy, użyłbym MessageBox i ErrorBox do wyświetlania komunikatów zamiast alertów gdzie się da

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/components/EditBar.tsx
> +import {MdDeleteForever, MdEdit} from "react-icons/md";
missing from package.json

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/components/ReviewCards.tsx
> +                    let feedback = deleted ? 'Review deleted successfully!' : 'Failed to delete review! Please try again...';
wymieszany język

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/components/ReviewCards.tsx
> +                    alert(feedback);
alerty to słaby user experience

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/lib/Review.ts
> +    const response = await api.delete((process.env.REACT_APP_API_ROOT + "/courses/" + courseId + "/reviews/" + username));
już nie trzeba dawać na początku REACT_API_ROOT, bez tego będzie czytelniej

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/lib/Review.ts
> +async function deleteReview(courseId: string, username: string) {
dodajemy anotacje typów

2023-12-27 16:22 UTC, mGarbowski commented on frontend/src/lib/utils.ts
>  export function getDummyReviews(): Review[] {
czy to jest jeszcze używane? chyba do wywalenia

2023-12-28 22:49 UTC, mbienkowsk commented on frontend/src/components/ReviewCards.tsx
> +                    alert(feedback);
taa, wiem, chcialem przerzucic sie na twojego errorboxa jak wrzucimy twoje zmiany na maina

2023-12-28 22:51 UTC, mbienkowsk commented on frontend/src/lib/utils.ts
>  export function getDummyReviews(): Review[] {
bez kita

2023-12-30 19:45 UTC, mGarbowski commented
trzeba domergować main bo było dużo zmian, jest już zaimplementowana funkcjonalność w backendzie

2024-01-04 10:12 UTC, mbienkowsk commented on frontend/src/components/ReviewCards.tsx
> +                    alert(feedback);
done

2024-01-04 16:09 UTC, mGarbowski approved these changes

2024-01-04 16:13 UTC, merged