87 frontend logic for editing reviews
mGarbowski/pap-projekt pull request #125
Opened 2023-12-26 11:46 UTC by mbienkowsk

seems very nice, but there's one issue - if we want admins to be able to edit regular users' opinions, it's gonna be a hassle with the way it's done now - but maybe we shouldn't? seems goofy ah for an admin to be able to edit what someone wrote, deleting is enough for moderating purposes, isn't it?

2024-01-05 13:36 UTC, mGarbowski requested changes
chyba trzeba dorobić endpoint do edytowania opinii

2024-01-05 13:36 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewService.java
> +        duplicate.ifPresent(reviewRepository::delete);
Absolutnie nie powinno być czegoś takiego,
POST służy do tworzenia nowego zasobu,
PUT służy do edytownaia istniejącego, nie powinno być tutaj usuwania

2024-01-05 13:38 UTC, mGarbowski commented
tu najpierw trzbea dodać endpoint do edytowania opinii #132 jest na  @MichLuszcz przypisany aktualnie

2024-01-05 13:43 UTC, mGarbowski commented on frontend/src/components/ReviewCards.tsx
> +function createReviewDeleteHandler(courseId: string, username: string, afterDeleting: Function, errorBoxSetter: Function): React.MouseEventHandler {
nie rozumiem do końca po co robić coś takiego? nie może to być funkcja wewnątrz komponentu i przekazana dalej jako lambda?

2024-01-05 13:44 UTC, mGarbowski commented on frontend/src/components/ReviewDetails.tsx
> +                   handleEdit={(_) => true}
🤔

2024-01-05 13:45 UTC, mGarbowski commented on frontend/src/components/ReviewDetails.tsx
> +function createCommentDeleteHandler(commentId: string, afterDeleting: Function, errorBoxSetter: Function): React.MouseEventHandler {
tu znowu chyba można zrobić to w środku komponentu i przekazać jako lambdę, jeśli to logicznie należy do komponentu to lepiej żeby było w środku imo

2024-01-05 13:47 UTC, mGarbowski commented on frontend/src/lib/ReviewComment.ts
> +    const response = await api.delete((process.env.REACT_APP_API_ROOT + "/comments/" + commentId));
bez REACT_API_ROOT

2024-01-05 13:49 UTC, mGarbowski requested changes
nie może być edytowania przez POST

2024-01-05 15:19 UTC, mbienkowsk commented on frontend/src/components/ReviewDetails.tsx
> +                   handleEdit={(_) => true}
to jest pod inne issue na edytowanie komentarzy, musialem podpiac zaslepke pod handleEdit po prostu

2024-01-05 15:24 UTC, mbienkowsk commented on frontend/src/components/ReviewCards.tsx
> +function createReviewDeleteHandler(courseId: string, username: string, afterDeleting: Function, errorBoxSetter: Function): React.MouseEventHandler {
chcialem poczatkowo zeby bylo wspolne do handlowania usuwania komentarzy i opinii, potem ogarnalem ze srednio i zostawilem na zewnatrz my bad

2024-01-05 15:25 UTC, mbienkowsk commented on frontend/src/components/ReviewCards.tsx
> +function createReviewDeleteHandler(courseId: string, username: string, afterDeleting: Function, errorBoxSetter: Function): React.MouseEventHandler {
no i bylo to 2 razy wieksze jak byly alerty, wiec lambda by miala ze 20 linijek, ale teraz tak to chyba przeklepie

2024-01-07 19:11 UTC, mGarbowski requested changes
porównywanie nulli!!!!

2024-01-07 19:11 UTC, mGarbowski commented on frontend/src/lib/utils.ts
> +}
czemu to jest dodane z powrotem?

2024-01-07 19:11 UTC, mGarbowski commented on frontend/src/pages/review/ReviewForm.tsx
> +        if (previousReview !== null) {
stary...

2024-01-07 19:11 UTC, mGarbowski commented on frontend/src/pages/review/ReviewForm.tsx
> +        previousReview === null ? ReviewService.postReview(request, courseId!) : ReviewService.editReview(request, courseId!, username);
🤬

2024-01-07 19:11 UTC, mGarbowski commented on frontend/src/pages/review/ReviewForm.tsx
> +        <h1>{previousReview === null ? "Napisz opinię" : "Edytuj swoją opinię"}
🙄

2024-01-07 19:27 UTC, mGarbowski approved these changes

2024-01-07 19:27 UTC, merged