minor fix
mGarbowski/pap-projekt pull request #130
Opened 2023-12-27 23:41 UTC by mGarbowski

2023-12-28 22:45 UTC, mbienkowsk commented on backend/src/main/java/pl/edu/pw/pap/review/Review.java
> +    private List<Comment> comments = new ArrayList<>();
shouldn't we use a hashset here, like in the other cases similar to this one?

2023-12-28 22:48 UTC, mbienkowsk requested changes
nie powiem ze rozumiem wszystko w pelni na tyle zeby skrytykowac, ze cos jest zle robione, ale ma sens dlaczego tak to wyglada w porownaniu do poprzedniego setupu i jest calkiem consistent poza tym ze w jednym miejscu zamiast hashsetu komentarze trzymane sa w arrayliscie, zmienilbym to/moze ja nie rozumiem skad tak jest i mozna mergowac

2023-12-28 23:07 UTC, mGarbowski commented
nwm, tak już wcześniej Michał napisał, ja nie widzę szczególnego powodu za jednym albo drugim

2023-12-29 14:54 UTC, mbienkowsk approved these changes
very nice

2023-12-29 14:54 UTC, merged