152 change review to include multiple criteria
mGarbowski/pap-projekt pull request #156
Opened 2024-01-06 21:27 UTC by mbienkowsk

introduced three criteria to grade the course:
* difficulty 
* how interesting they are
* engagement they require

2024-01-06 21:51 UTC, MichLuszcz reviewed
jeśli chodzi o frontend to nie jestem pewien czy jest wszystko bo nie znam całej struktury ale te zmiany które widzę są sensowne jak na moje oko

2024-01-07 13:04 UTC, mGarbowski commented on backend/src/test/java/pl/edu/pw/pap/teacher/TeacherIntegrationTests.java
> +        assertEquals(5.5, (double) (json.read("$.averageEaseRating")));
double może być bezpieczniej porównywać z zadaną dokładnością, można ją podać jako 3 argument do assertEquals

2024-01-07 13:05 UTC, mGarbowski commented on frontend/src/lib/Course.ts
> +    averageEaseRating: string,
string a nie jakiś typ liczbowy?

2024-01-07 13:06 UTC, mGarbowski commented on frontend/src/lib/utils.ts
> +        easeRating: "9",
to już nie jeest od dłuższego czasu do wywalenia?

2024-01-07 13:07 UTC, mGarbowski commented on frontend/src/pages/review/ReviewForm.tsx
> +                value={rating !== null ? rating : 0}
czumpiiii
było dobrze, nie robimy tak

2024-01-07 13:08 UTC, mGarbowski commented on frontend/src/pages/review/ReviewForm.tsx
> +        if ([easeRating, interestRating, engagementRating].some(r => r === null)) return; // todo: indicate to the user that they need to rate numerically
i tu też

2024-01-07 13:10 UTC, mGarbowski requested changes
Super, bardzo dużo było do zmiany i bardzo mi się podoba, tylko porównywanie z `null` w typescripcie trzeba poprawić i można mergować, reszta to mało istotne uwagi

2024-01-07 13:14 UTC, mGarbowski approved these changes
była szybka zmiana więc sam poprawiłem

2024-01-07 13:15 UTC, mGarbowski commented
przeczytaj uwagi i można mergować

2024-01-07 13:47 UTC, MichLuszcz commented on backend/src/test/java/pl/edu/pw/pap/teacher/TeacherIntegrationTests.java
> +        assertEquals(5.5, (double) (json.read("$.averageEaseRating")));
poprawione, przy okazji dodałem taki sam check w courseIntegrationTests

2024-01-07 17:30 UTC, mbienkowsk commented on frontend/src/pages/review/ReviewForm.tsx
> +                value={rating !== null ? rating : 0}
pardonsik

2024-01-07 17:36 UTC, mbienkowsk commented on frontend/src/lib/utils.ts
> +        easeRating: "9",
wywalone

2024-01-07 17:37 UTC, mbienkowsk commented on frontend/src/lib/Course.ts
> +    averageEaseRating: string,
tez sie zastanawilaem, ale zawsze byly stringi i jakos wzialem to za poprawne po prostu, zrobie w innym issue

2024-01-07 17:42 UTC, merged