144 implement Report system in backend
mGarbowski/pap-projekt pull request #171
Opened 2024-01-08 22:45 UTC by MichLuszcz

Powinno działać, dodane metody do pobierania, usuwania i dodawania razem z testami na wszystko

2024-01-08 22:46 UTC, MichLuszcz commented
Model zmieniony na taki który nie trzyma w sobie relacji do Review i Comment i User, tylko ma czyste dane. Usuwanie zbędnych reportów obsługiwane w ReviewService i CommentService

2024-01-09 13:15 UTC, mGarbowski commented
czemu testy frontendu nie przechodzą xdd

2024-01-09 13:18 UTC, mGarbowski commented
dobra, to coś z serwerami githuba

2024-01-09 13:46 UTC, mGarbowski requested changes
Nie rozumiem paru rzeczy to proszę o odpowiedź i najlepiej jakby przy wszystkich tych fragmentach które są zrobione nie tak jak chcemy docelowo to żeby tam poozstawiać jakieś komentarze i TODO żeby było potem waidomo co naprawiać

i potem nie mergujmy tego brancha tylko ja go sobie zaciągnę na brancha z frontendem do tego się je zmerguje razem jak będę mieć pewność że to się nie wykrzaczy

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/Comment.java
> +//    private Set<CommentReport> reports = new HashSet<>();
jak to i tak nie działa i nie jest używane to bym wywalił zakomentowany kod

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/report/CommentReportRepository.java
> +    Long removeByCommentId(Long commentId);
czemu to zwraca Long?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportController.java
> +        return reportService.reportComment(commentId, reportRequest, userPrincipal); // links added in service
czemu dodawanie linków w service?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportDTO.java
> +    //data
?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +        ArrayList<ReportDTO> allReports = new ArrayList<>(reviewReports
niepotrzebnie jest wołany konstruktor na istniejącej liście

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +        return allReports.stream().toList();
po co `.stream().toList()`?!

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +    public ReportDTO convertReviewReportToDto(ReviewReport report) {
a jakby napisać przeciążaną metodę (żeby 2 razy nazywała się tak samo ale przyjmowała różne parametry)?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewService.java
> +        reviewReportRepository.removeByCourseIdAndReviewerUsername(
trzeba jakieś TODO w tych miejscach zostawić bo docelowy nie chcemy żeby tak było

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/report/ReportController.java
> +    public ResponseEntity<Exception> handleDuplicateReview(Exception e) {
Czemu to w ogóle jest tutaj?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/report/ReviewReportRepository.java
> +    Long removeByCourseIdAndReviewerUsername(Long courseId, String reviewerUsername);
znowu, czemu Long?

2024-01-09 13:46 UTC, mGarbowski commented on backend/src/test/java/pl/edu/pw/pap/comment/CommentIntegrationTest.java
> +        System.out.println("deleting");
nie używamy System.out tylko loggera

2024-01-09 14:40 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportDTO.java
> +    //data
przez chwile mi sie pomyliło i myślałem że dto będą trzymać te linki jako pola i dlatego sobie oddzieliłem data od links ale potem poszedłem po rozum do głowy i zostało sama data. usunę ten komentarz bo nic nie wnosi

2024-01-09 14:43 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportController.java
> +    public ResponseEntity<Exception> handleDuplicateReview(Exception e) {
pardonsik, kopiowałem sobie handlery z innego kontrolera

2024-01-09 14:57 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +        ArrayList<ReportDTO> allReports = new ArrayList<>(reviewReports
chodzi o to że reviewReports jest typu List, który nie obsługuje dodawania nowych elementów bo jest niemutowalny, więc tworze sobie ArrayList i najpierw dodaje zawartość z reviewReports a potem z commentReports. ArrayLista allReports nie istnieje nigdzie wcześniej. Wydawało mi się to najbardziej sensownym rozwiązaniem. Wydaje mi się to lepszym rozwiązaniem niż np. rzutowanie

2024-01-09 15:03 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportController.java
> +        return reportService.reportComment(commentId, reportRequest, userPrincipal); // links added in service
Dodawanie linków w serwisie jest dlatego, że musi się dziać w momencie konwertowania na DTO, żeby mieć dostęp do orginalnych obiektów. Chodzi o to, że link do "entity" używa innych Controller'ów więc musi wiedzieć jakiego typu Report dostaje. Link do "self" też używa innych metod Controllera w zależności od typu konwertowanego Reportu.  W teorii dodawanie linku do "review" mógłbym wyciągnąć do ReportControllera ale raz że trzeba by te rzeczy dodatkowo umieszczać w ReportDTO a i tak większość linków muszę tworzyć w ConvertToDto.

2024-01-09 15:05 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewService.java
> +        reviewReportRepository.removeByCourseIdAndReviewerUsername(
pododawałem w Review, ReviewReport, Comment, CommentReport, ReviewService (przy usuwaniu), CommentService (przy usuwaniu),

2024-01-09 15:09 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/comment/report/CommentReportRepository.java
> +    Long removeByCommentId(Long commentId);
Metody remove i delete mogą zwracać Long albo np List. W tym wypadku zwraca liczbę usuniętych rekordów. Jeśli byłoby mapowane na List to zwracałoby usunięte rekordy. Stwierdziłem że nie zawadzi zwracać tego, ale aktualnie tej zwracanej liczby nie wykorzystuje więc można dać void, nic to nie zmieni w zachowaniu samego usuwania.

2024-01-09 15:10 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/report/ReviewReportRepository.java
> +    Long removeByCourseIdAndReviewerUsername(Long courseId, String reviewerUsername);
do metod Repozytoriów delete i remove można dać Long albo List i wtedy zwracają dodatkowe info o usuniętych rekordach. Przy Long jest to liczba usuniętch rekordów a przy List są to te usunięte rzeczy.

2024-01-09 15:11 UTC, MichLuszcz commented on backend/src/test/java/pl/edu/pw/pap/comment/CommentIntegrationTest.java
> +        System.out.println("deleting");
to miało być tymczasowe ale zapomniałem o tym, usunięte już

2024-01-09 15:15 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/comment/Comment.java
> +//    private Set<CommentReport> reports = new HashSet<>();
usunięte, zapomniałem o tym

2024-01-09 15:16 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +    public ReportDTO convertReviewReportToDto(ReviewReport report) {
dobry pomysł, zmieniłem na takie

2024-01-09 15:53 UTC, closed without merging

2024-01-09 15:55 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/report/ReportService.java
> +        return allReports.stream().toList();
Troche nie byłem pewien jak ta relacja między ArrayList a List działa, ale faktycznie niepotrzebne