33 endpointy do pobierania dodawania opinii i komentarzy
mGarbowski/pap-projekt pull request #73
Opened 2023-12-01 21:37 UTC by MichLuszcz

NIE Mergować dopóki nie zostaną zrobione testy jednostkowe i integracyjne przez @Sawertynn .

2023-12-01 22:44 UTC, mGarbowski commented
jeśli logika w serwisach nie jest skomplikowana to wystarczą testy integracyjne @Sawertynn

2023-12-02 18:59 UTC, mGarbowski requested changes
Generalnie very nice,
w paru miejscach nie jestem pewien czy jest dobra logika
w wielu mi sie estetycznie nie podoba ale jest dobrze

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/Comment.java
> +        System.out.println("removed comment " + this.id + " from user");
Jak coś wypisujemy to przez wstrzyknięcie odpowiedniego Loggera

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/commentNotFoundException.java
> +public class commentNotFoundException extends RuntimeException {
Nazwy klas wielką literą

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +            throw new commentNotFoundException("No comment with Id" + commentId);
w przypadku usuwania, próba usunięcia nieistniejącego zasobu powinna zwrócić 204 No Content a nie 404 Not Found

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +        System.out.println("Trying to get user with username: " + principal.getUsername());
logger, nie print

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +        if (!comment.getUser().getId().equals(user.getId())) {
a co jeśli jest adminem

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +        if (maybeUser.isEmpty()){
Zamiast używać `.ifPresent()` / `.ifEmpty()` i potem `.get()` to są metody, które pozwalają bardziej elegancko to pisać jak np `.orElseThrow(...)`

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +        if (getUser.isEmpty()) {
`.orElseThrow(...)`

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/AddCommentRequest.java
> +public record AddCommentRequest(String text, Long courseId, String username) {
Skoro mamy `UserPrincipal` to chyba w ogóle nie potrzeba tu dawać username(?)

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentController.java
> +    public Comment addComment(@RequestBody AddCommentRequest request, @AuthenticationPrincipal UserPrincipal principal) {
w tym momencie jakiś username mamy w URL, request i principal

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/course/courseNotFoundException.java
> +public class courseNotFoundException extends RuntimeException {
Nazwy klas wielką literą

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @GetMapping("/api/courses/{courseId}/users/{username}/reviews")
ja bym dał `/api/courses/{courseId}/reviews/{username}`, niespójne z tym co jest niżej

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +        System.out.println("returning review with id " + review.id.courseId + " " + review.id.userId);
logger

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @PostMapping("/api/courses/{courseId}/users/{username}/reviews")
i tu niespójny URL

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @DeleteMapping("/api/courses/{courseId}/users/{username}/reviews")
i tu

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @ExceptionHandler({commentNotFoundException.class, userNotFoundException.class, reviewNotFoundException.class})
może zrobić wspólną klasę bazową EntityNotFoundException

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/user/User.java
>      @OneToMany(mappedBy = "user", fetch = FetchType.EAGER)
bez `@JsonIgnore` ?

2023-12-02 18:59 UTC, mGarbowski commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewService.java
> +            System.out.println("Found user of review being deleted");
logger

2023-12-04 21:47 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewService.java
> +            System.out.println("Found user of review being deleted");
Wszystkie system.outy zostały albo zmienione na loggera albo wyrzucone całkowicie jeśli nie były specjalnie potrzebne

2023-12-04 21:57 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +        if (!comment.getUser().getId().equals(user.getId())) {
Dodałem check  żeby sprawdzał czy jeśli nie ma zgodności nazw użytkowników to czy użytkownik żądający nie jest też adminem. Jeśli nie jest to nie przechodzi dalej

2023-12-04 21:59 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @GetMapping("/api/courses/{courseId}/users/{username}/reviews")
done

2023-12-04 22:00 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @PostMapping("/api/courses/{courseId}/users/{username}/reviews")
zmienione na /api/courses/{courseId}/reviews/{username}

2023-12-04 22:01 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/review/ReviewController.java
> +    @DeleteMapping("/api/courses/{courseId}/users/{username}/reviews")
zmienione na /api/courses/{courseId}/reviews/{username}

2023-12-04 22:03 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/user/User.java
>      @OneToMany(mappedBy = "user", fetch = FetchType.EAGER)
Co prawda ja tutaj akurat na tym branchu nie robiłem za bardzo, to z racji że ma przeciążony toString, i definiujemy własne endpointy, to akurat nie jest to automatycznie wrzucane do Jsonów więc nie ma potrzeby. Jedyny dostęp do tego jest przez link do innej metody kontrolera. Nie ma ryzyka pętli w aktualnej konfiguracji

2023-12-04 22:52 UTC, MichLuszcz commented on backend/src/main/java/pl/edu/pw/pap/comment/CommentService.java
> +            throw new commentNotFoundException("No comment with Id" + commentId);
fixed

2023-12-07 11:31 UTC, mGarbowski approved these changes
ujdzie

2023-12-07 11:32 UTC, merged