79 przeglądanie komentarzy i opinii
mGarbowski/pap-projekt pull request #91
Opened 2023-12-07 11:34 UTC by mbienkowsk

2023-12-07 11:46 UTC, MichLuszcz commented on frontend/src/components/CommentList.tsx
> +interface CommentCardProps {
Według mnie wszystkie typy danych/interfejsy używane w jakichś funkcjach powinny być nad tą funkcja/klasą/whatever żeby było bardziej czytelne

2023-12-07 12:00 UTC, MichLuszcz commented on frontend/src/components/CourseList.tsx
> +        <td style={{textAlign: 'right'}}>{NUM_REVIEWS_PLACEHOLDER}</td>
Add todo to rememmebr to change the placeholder

2023-12-07 22:13 UTC, mGarbowski requested changes
Very nice, ale kilka rzeczy do poprawy

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/App.tsx
> +                                <Route path="comments/:authorUsername" element={<SingleReview/>}/>
reviews a nie comments

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/CourseDetails.tsx
> +    const typeContent = <p className="CourseInfo">Typ kursu: {course.type}</p>
jak nie robimy przypisywania warunkowego to ja bym takie elementy dawał już po `return`

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/CourseDetails.tsx
> +    const moduleContent = course.module !== null
jak porównujemy czy coś nie jest nulem to przez `!=` a nie `!==`

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/CourseList.tsx
> +            <td>Nazwa</td>
W nagłówkach tabel używamy `<th>` zamiast `<td>` https://www.w3schools.com/TAGs/tag_th.asp

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/CourseList.tsx
> +        <td style={{textAlign: 'right'}}>{course.averageRating}</td>
róbmy to po ludzku w oddzielnym pliku css

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/TeacherList.tsx
> +            <td>Nazwisko</td>
<th>

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/components/TeacherList.tsx
> +        <td style = {{textAlign: 'right'}}>
i znowu do pliku css

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/lib/Review.ts
> +    return await api.get(course._links.reviews.href)
dawanie async/await chyba nie jest potrzebne jeśli api.get zwraca promise,
cały sens async/await jest taki, że nie trzeba chainować metod i można pisać "normalnie"

2023-12-07 22:13 UTC, mGarbowski commented on frontend/src/lib/ReviewComment.ts
> +async function fetchCommentsByReview(review: Review) {
anotujemy jaki typ będzie zwracany

2023-12-07 22:56 UTC, mbienkowsk commented on frontend/src/App.tsx
> +                                <Route path="comments/:authorUsername" element={<SingleReview/>}/>
gg, robilem analogicznie jak w api

2023-12-07 23:23 UTC, mbienkowsk commented
poprawionyy

2023-12-08 00:10 UTC, MichLuszcz commented
Beany nie wykomentowane pewnie i testy backendowe się wywróciły na twarz znowu xD

2023-12-08 12:00 UTC, mGarbowski approved these changes

2023-12-08 12:00 UTC, merged